### ISSUE TITLE
Southpaw PCB Version

### ISSUE THREAD

**Issue by julieminer** [mizma/flatbox#1]
Would it be possible to create a southpaw version of the PCB? I don't know enough about PCB design to feel confident in making changes.

**Comment by mizma** [comment]
Thanks for your feedback.
Never seen a southpaw layout of an arcade controller though. do you have some examples?
It may be possible, but I am also just a hobbyist making stuff so I might consider when I have time.

**Comment by julieminer** [comment]
@mizma For sure! It's essentially just a horizontally mirrored layout, with movement on the right hand: 
![APJxihkmWuQxAAAAAElFTkSuQmCC](https://github.com/mizma/flatbox-acr/assets/3271813/a610f56c-bfcd-4462-97da-1530c9803262)

No worries if not, I took a stab at making my own based on the included files, but definitely don't feel confident enough that I've done any of it right.

**Comment by mizma** [comment]
Thanks for the info!
It might not be easy to make by just reversing the buttons but it might be easier to remap all the buttons and re-layout the data.

In my experience, it is important to make the CAD drawings first and make a clear positioning of all components, then use the CAD data to make the PCB cutout and layout the buttons and pin-headers for the arduino board.

1. first make the reversed button layout data in FreeCAD, create a measurement drawing so I know where exactly I have to place each button from top right corner
2. export the board edge from FreeCAD and import it into KiCAD to make the board edge-cut layer
3. place the buttons + AVR board foot print to the exact locations as described in 1.
4. wire the pins (It may be possible to wire all the buttons the same as the original, but wires will have to cross over a lot.  maybe easier to just place the buttons whereever is easiest to wire to, and re-build the firmware button mapping to match the result.)
5. (Optional) put ground fills, and put throughhole vias in those ground fills (edges, islands, corners etc)
6. (Optional) put Silk screen to mark buttons, put Logos etc to pretty the PCB

That's the process I ended up using.  It may not be the best, but it worked for me.
I might consider making Southpaw version when I have time to work on the additional attack button version, but It maybe a bit further down the line. Sorry.

**Comment by mizma** [comment]
@taffyrat I have made a new 11 button leverless controller of similar type.  On this one, I made the PCB reversible, so it should be possible to just flip the board and implement the buttons on the reverse side to make it into a southpaw version.

https://github.com/mizma/ergoSHIFT/

The project is not yet completed (I have just ordered the PCB etc. so not tested), but please take a look.

**Comment by mizma** [comment]
Please take a look at the 11 button version and see if that fits your needs.
Otherwise, I might take some time in the future (after ergoSHIFT is done), to make this flatbox-acr version reversible as well.

**Comment by julieminer** [comment]
That looks great, thanks for letting me know! Super excited to see it in action. Feel free to close this issue!
